---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: save username 
    command: whoami
    become: false
    register: username
    ignore_errors: true
  
  - import_playbook: "{{ playbook_dir }}/debian/golang/tasks/main.yml"