---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: save username 
    command: whoami
    become: false
    register: username
    ignore_errors: true
  
  - name: downloading virtualBox deb
    command: wget https://download.virtualbox.org/virtualbox/7.0.10/virtualbox-7.0_7.0.10-158379~Debian~bookworm_amd64.deb
  
  - name: installing virtual-Box .deb
    command: dpkg -i virtualbox-7.0_7.0.10-158379~Debian~bookworm_amd64.deb
    ignore_errors: true
  
  - name: Run apt --fix-broken install 
    command: apt --fix-broken install
  
  - name: install packages
    package: 
      name: 
        - virtualbox-7.0 