---
- hosts: local
  roles:
     - role: gantsign.golang
       golang_gopath: '$HOME/workspace-go'
  connection: local
  become: true

  tasks:
  - name: save username 
    command: whoami
    become: false
    register: username
    ignore_errors: true