---
- hosts: localhost
  connection: local
  become: true
  roles:
     - role: gantsign.golang
       golang_gopath: "$HOME/workspace-go"
  

  tasks:
  - name: save username 
    command: whoami
    become: false
    register: username
    ignore_errors: true