---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: save username 
    command: whoami
    become: false
    register: username
    ignore_errors: true

  - name: installing nvm
    command: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh