---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: save username 
    command: whoami
    become: false
    register: username
    ignore_errors: true
  
  - name: downloading go .tar file
    command: ansible-playbook "{{ playbook_dir }}/golang/tasks/main.yml"