---
- hosts: localhost
  connection: local
  become: yes
  roles:
    - role: gantsign.golang
      golang_gopath: "$HOME/workspace-go"

  tasks:
    - name: save username
      command: whoami
      become: no
      register: username
      ignore_errors: yes

    - name: Set Go PATH
    environment:
      PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
    become: no
    ignore_errors: yes

    - name: Run a Go command
      command: /usr/local/go/bin/go version
      become: no
      register: go_version
      ignore_errors: yes

    - name: Display Go version
      debug:
        var: go_version.stdout